config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new]
  end
  resources :posts, except: [:index, :new] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :author, :post, presence: true

  belongs_to(
  :author,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: "User"
  )

  belongs_to(
  :post,
  primary_key: :id,
  foreign_key: :post_id,
  class_name: "Post"
  )

  has_many(
  :child_comments,
  primary_key: :id,
  foreign_key: :parent_comment_id,
  class_name: "Comment"
  )

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author, presence: true

  has_many(
    :post_subs,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: "PostSub",
    inverse_of: :post
  )

  has_many(
    :subs,
    through: :post_subs,
    source: :sub
  )

  belongs_to(
    :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: "User"
  )

  has_many :comments

  def comments_by_parent_id
    comments = Hash.new { |h, k| h[k] = [] }

    self.comments.each do |comment|
      comments[comment.parent_comment_id] << comment
    end

    comments
  end
end

app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post, :sub, presence: true

  belongs_to :post
  belongs_to :sub


end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, :moderator, presence: true

  belongs_to(
    :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: "User"
  )

  has_many(
    :post_subs,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: "PostSub"
  )

  has_many :posts,
    through: :post_subs,
    source: :post

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token
  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  has_many(
    :moderated_subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: "Sub"
  )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def current_user
    @current_user = User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create

    @comment = Comment.new(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to comment_url(@comment.parent_comment_id)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signed_in
  before_action :require_author, only: [:edit, :update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @all_comments = @post.comments_by_parent_id # @post.comments.includes(:author)
  end

  def edit
    @post = Post.find(params[:id])

  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  private

  def require_author
    @post = Post.find(params[:id])
    unless @post.author == current_user
      flash[:errors] = ["Only author can edit this post"]
      redirect_to post_url(@post)
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      sign_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["invalid login information"]
      render :new
    end
  end


  def destroy
    sign_out
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_signed_in
  before_action :require_moderator, only: [:edit, :update]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user
    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator
    @sub = Sub.find(params[:id])
    unless @sub.moderator == current_user
      flash[:errors] = ["Only moderator can edit sub"]
      redirect_to sub_url(@sub)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    <<-HTML.html_safe
      <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
    HTML
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<ul>

  <li> <a href="<%= comment_url(comment) %>"><%= comment.content %></a> - User: <%= comment.author.username %> - <%= comment.created_at %></li>

    <% @all_comments[comment.id].each do |child_comment| %>
    <% if child_comment.parent_comment_id == comment.id %>
    <%= render "comments/comment", comment: child_comment  %>
    <% end %>
    <% end %>

</ul>

app/views/comments/new.html.erb
<h1>Add Comment</h1>
<form class="" action=" <%= comments_url %> " method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">
  <label for="">Content
    <input type="text" name="comment[content]" value=" <%= @comment.content %> ">
  </label>

  <input type="submit" name="" value="Create Comment">
</form>

app/views/comments/show.html.erb
<p><%= @comment.content %></p>
<p>Authored by: <%= @comment.author.username %></p>
<form class="" action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <label for="">Comment
    <input type="text" name="comment[content]" value="">
  </label>
  <br>

  <input type="submit" name="" value="Add child comment">
</form>

<%= render 'comment', comment: @comment %>

<a href="<%= subs_url %>">All subs</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>
  <% if signed_in? %>
    <p>Hello, <%= current_user.username %>!</p>
    <form class="" action="<%= session_url %>" method="post">
      <%= auth_token %>
      <input type="hidden" name="_method" value="delete">
      <input type="submit" name="" value="Log Out">
    </form>
  <% else %>
    <a href="<%= new_user_url %>">Create New User</a>
    <a href="<%= new_session_url %>">Log In</a>
  <% end %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post!!!</h1>

<form class="" action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>


  <label for="">Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label for="">URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label for="">Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>
  <br>
  <label>Subs</label>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
              value="<%= sub.id %>"
              name="post[sub_ids][]"
              <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    </label>
  <% end %>
  <br>
  <input type="submit" name="" value="Edit Post">
</form>

app/views/posts/new.html.erb
<h1>New Post!!!</h1>

<form class="" action="<%= posts_url %>" method="post">
  <%= auth_token %>
  <!-- <input type="hidden" name="post[sub_id]" value="<%#= params[:sub_id] %>"> -->

  <label for="">Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label for="">URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label for="">Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>
  <br>

  <label>Subs</label>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
              value="<%= sub.id %>"
              name="post[sub_ids][]"
              <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    </label>
  <% end %>
  <br>

  <input type="submit" name="" value="Add Post">
</form>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Author: <%= @post.author.username %></p>
<p>URL: <%= @post.url %></p>
<p>Content: <%= @post.content %></p>

<p>Subs</p>
<ul>
  <% @post.subs.each do |sub| %>
  <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>
<a href="<%= edit_post_url(@post) %>">Edit Post</a>


<p>Parent Comments</p>

  <% @all_comments[nil].each do |comment| %>

  <%= render "comments/comment", comment: comment  %>

  <% end %>



<a href="<%= new_post_comment_url(@post) %>">New Comment</a>

app/views/subs/edit.html.erb
<h1>Edit Sub!!!</h1>

<form class="" action="<%= sub_url(@sub) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="patch">

  <label for="">Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label for="">Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <input type="submit" name="" value="Edit Sub">
</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>

<a href="<%= new_sub_url %>">Create new sub!</a>

app/views/subs/new.html.erb
<h1>New Sub!!!</h1>

<form class="" action="<%= subs_url %>" method="post">
  <%= auth_token %>

  <label for="">Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label for="">Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <input type="submit" name="" value="Create Sub">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>

<!-- TODO: POSTS HERE -->
<ul>

<% @sub.posts.each do |post| %>

  <li> <a href="<%= post_url(post) %>"><%= post.title %></a></li>

<% end %>
</ul>
<a href="<%= new_sub_post_url(@sub) %> ">Add post</a>

<a href="<%= edit_sub_url(@sub) %>">Edit sub</a>
<a href="<%= subs_url %>">All subs</a>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up">
</form>